version: '3.7'

services:

  e-commerce-backend:
    container_name: e-commerce-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678